language: c
sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

env: 
  - OPTIONS="--enable-static=yes --enable-shared=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-mod-x11=yes --enable-mod-ffi=yes"

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTIONS="--enable-static=yes --enable-sharee=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-mod-x11=no --enable-mod-ffi=no"

script:
  - touch -r moo/configure moo/* moo/*/* && cd moo && ./configure $OPTIONS && make && make check