language: c
sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

env: 
  - OPTIONS="--enable-static --disable-shared --enable-dynamic-module --enable-static-module --enable-unicode=yes:2"
  
matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTIONS="--enable-static --disable-shared --enable-dynamic-module --enable-static-module --enable-unicode=yes:2 --disable-mod-x11 --disable-mod-ffi"

script:
  - touch -r moo/configure moo/* moo/*/* && cd moo && ./configure $OPTIONS && make