language: c
sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
    - OPTIONS="--enable-static=yes --enable-shared=no --enable-debug=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=yes --enable-shared=no --enable-debug=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:4 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=no --enable-shared=yes --enable-debug=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=no --enable-shared=yes --enable-debug=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:4 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=yes --enable-shared=no --enable-debug=yes --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=yes --enable-shared=no --enable-debug=yes --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:4 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=no --enable-shared=yes --enable-debug=yes --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"
    - OPTIONS="--enable-static=no --enable-shared=yes --enable-debug=yes --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:4 --enable-full-liw=no --enable-mod-con=yes --enable-mod-sck=yes --enable-mod-ffi=yes --enable-mod-x11=yes --enable-pthread-flags=yes"

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTIONS="--enable-static=yes --enable-shared=no --enable-dynamic-module=yes --enable-static-module=yes --enable-wide-char=yes:2 --enable-full-liw=no --enable-mod-con=no --enable-mod-sck=yes --enable-mod-ffi=no --enable-mod-x11=no --enable-pthread-flags=yes"

script:
  - touch -r moo/configure moo/* moo/*/* && cd moo && ./configure $OPTIONS && make && make check